name: Publish Aggregated RSS to GitHub Pages

on:
  schedule:
    - cron: '0 15 * * 5' # Runs at 3 PM UTC every Friday, which corresponds to 9 AM CST
  workflow_dispatch: # Allows manual triggering
  push:
    branches:
        - 'main'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0 # Fetches all history for .Git Info and tags

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install feedparser requests
        pip install feedparser requests pytz

    - name: Generate Aggregated RSS Feed
      run: python aggregate_rss.py

    - name: Publish to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages
        publish_dir: ./ # Or the directory where your RSS file is saved
    
    - name: Output GitHub Pages URL
      run: echo "Your aggregated RSS feed is published at https://ekbrothers.github.io/aggregated-devops-rss/"
